# ================================
# 🌐 Personal Portfolio Configuration
# Author: Rashed Hassan
# ================================

# --- Site Settings ---
title: "Rashed Hassan | Digital Marketer"
description: "Professional Freelance Digital Marketer | SEO • PPC • Social Media • Funnels"
baseurl: "" # Leave empty for root domain
url: "https://edwardrashed.com" # Change if using custom domain

# --- Author Info ---
author:
  name: "Rashed Hassan"
  email: "rashedhassanpro@gmail.com"
  location: "Bangladesh 🌍"
  phone: "+8801774521332"
  linkedin: "https://linkedin.com/in/edwardrashed"
  github: "https://github.com/rashedhassanpro"
  fiverr: "https://fiverr.com/edwardrashed"
  upwork: "https://www.upwork.com/freelancers/~rashedhassan"
  social:
    facebook: "https://www.facebook.com/rashed.hasan.pro"
    instagram: "https://www.instagram.com/rashedhassan.pro"
    threads: "https://www.threads.com/@rashedhassan.pro"
    x: "https://x.com/rashedhassanpro"

# --- Theme Settings ---
theme: jekyll-theme-cayman # You can also try: minima, slate, modernist, etc.

# --- Branding Colors ---
# Adjust colors to match your personal brand
colors:
  primary: "#1F2937" # Dark Gray for text
  accent: "#3B82F6"  # Blue for links/buttons
  background: "#F9FAFB" # Light background
  highlight: "#FBBF24"  # Yellow for highlights

# --- Navigation Menu ---
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Services"
    url: "/services"
  - title: "Portfolio"
    url: "/portfolio"
  - title: "Contact"
    url: "/contact"

# --- SEO & Analytics ---
google_analytics: "UA-XXXXXXXXX-X" # Add your Google Analytics tracking ID
seo:
  twitter_username: "rashedhassanpro"
  linkedin_profile: "edwardrashed"
  facebook_profile: "rashed.hasan.pro"

# --- Plugins ---
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# --- Pagination ---
paginate: 5
paginate_path: "/blog/page:num"

# --- Markdown & Code Settings ---
markdown: kramdown
highlighter: rouge

# --- Build Settings ---
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# --- Footer ---
footer:
  text: "© 2025 Rashed Hassan | Designed with ❤️ using Jekyll & GitHub Pages"
  show_social_icons: true
